---
language: swift
os: osx
osx_image: xcode12.3
script: "xcodebuild clean build test -project DemoCicd/DemoCicd.xcworkspace -scheme \"DemoCicd\" -sdk iphonesimulator -destination \"platform=iOS Simulator,OS=14.3,name=iPhone XR” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO"

