# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoCicd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoCicd
   pod 'Kingfisher', '~> 6.0'


  target 'DemoCicdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoCicdUITests' do
    # Pods for testing
  end

end
